---
- name: install Tomcat server
  hosts: servers
  remote_user: 
  tasks:
    - name: update system
      yum:
        update_only: yes
        update_cache: yes
    - name: install aphache
      yum:
        name: httpd
    - name: start apache
      service:
        name: httpd
        state: started
        
        
